version: '3.5'
services:
  contact-svc:
    container_name: ${CONTAINER_NAME}
    image: "${AWS_ECR_URL}/${CONTAINER_NAME}:${UNIQUE_IMAGE_TAG}"
    build:
      context: .
    ports:
      - "${TARGET_PORT}:${CONTAINER_PORT}"
    environment:
      - GATEWAY_URL=${GATEWAY_URL}
      - JWT_KEY=${JWT_KEY}
      - PORT=${CONTAINER_PORT}
